version: '3.4'

services:
  registone.logcenter.api:
    container_name: registonelogcenterapi
    image: registonelogcenterapi
    environment: 
        - PORT=5000
    ports:
        - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
